<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>PermadB.Uninstaller</RootNamespace>
    <AssemblyName>Uninstall</AssemblyName>
    <AssemblyTitle>PermadB Uninstaller</AssemblyTitle>
    <Version>1.0.0</Version>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
